[WIP]商品詳細表示 機能の実装
koemaru/fleamarket_sample_80b pull request #23
Opened 2020-11-12 15:31 UTC by koemaru

# What
 - 商品詳細ページから商品購入ページへのリンクを実装
    - 出品者以外にしか商品購入ページへのリンクは踏めない
    - ログインしていない場合はログイン画面に遷移
 - 出品者が出品した商品の詳細を確認できるページを実装
    - 編集・削除のリンクは出品者にしか踏めない
    - ログインしていない場合はログイン画面に遷移

# Why
商品詳細ページから商品購入ページに遷移できるようにするため。
出品した商品の詳細を確認できるようにするため。

2020-11-12 15:47 UTC, mikan-juice requested changes

2020-11-12 15:47 UTC, mikan-juice commented on app/views/products/show.html.haml
> +          - else
elsifの下にelseがあるのはなぜですか？

2020-11-13 11:00 UTC, koemaru commented on app/views/products/show.html.haml
> +          - else
elseによりログインしてない場合にも「購入画面に進む」が表示されます。実際にメルカリでもログインしていない場合に「購入画面に進む」は表示されます。ちなみに、メルカリでは、ログインしていない状態でこの「購入画面に進む」をクリックするとログイン画面に遷移します。今回のFURIMAでもログインしていない状態で「購入画面に進む」をクリックするとログイン画面に遷移するように実装しています。

2020-11-13 12:05 UTC, mikan-juice commented on app/views/products/show.html.haml
> +          - else
なるほど！わかりました。

2020-11-13 12:27 UTC, TOMARUMARU reviewed
LGTMです。お疲れ様でした。mergeして次に進みましょう。

2020-11-13 12:32 UTC, merged